[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sol_usd_oracle = "BqNxx8MrVnHbvJHPgCMPdY2HNKcPiHk47zm98WY4Ch8Z"
token_minter = "493fewz6VEwuQ7UrpyMs3iNbC2Yih1ca1923K5iiroaX"

[programs.devnet]
sol_usd_oracle = "BqNxx8MrVnHbvJHPgCMPdY2HNKcPiHk47zm98WY4Ch8Z"
token_minter = "493fewz6VEwuQ7UrpyMs3iNbC2Yih1ca1923K5iiroaX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
litesvm = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
